console.log("Hello", "String" )
console.log(true, "Boolean" )
console.log("Name", "String" )
console.log(33, "Number" )
console.log("90", "String"  )
console.log(90+"77", "String" )
console.log( {name:'Anu', age:15}, "Object"  )
console.log(false, "Boolean" )
console.log(1655/5, "Number" )
console.log(["javascript", "html", "css"], "Array")